project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd

format:
  html:
    theme: cyborg
    toc: false
    css: styles/styles.css

editor: visual

