project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd

format:
  html:
    theme: cyborg
    toc: false
    css: styles/styles.css

editor: visual

include-in-header:
  - text: |
      <!-- from https://css-tricks.com/emoji-as-a-favicon/ -->
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>ðŸ§ª</text></svg>">

      